services:
  - type: web
    name: job-tracker
    runtime: python
    pythonVersion: "3.11" 
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://job-tracker.onrender.com
      - key: BACKEND_PORT
        value: 5001